"""create users table

Revision ID: 0be6af0e006c
Revises: 53ca878bd911
Create Date: 2026-01-17 19:12:16.374391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0be6af0e006c'
down_revision: Union[str, Sequence[str], None] = '53ca878bd911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('username', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
                    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[
                    ], postgresql_nulls_not_distinct=False),
                    sa.UniqueConstraint('username', name=op.f(
                        'users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column("posts", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key('fk_posts_user_id_users',
                          'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_posts_user_id_users', 'posts', type_='foreignkey')

    op.drop_column("posts", 'user_id')

    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
