"""add images field

Revision ID: 3a829c6ec388
Revises: f3d1ff4fb5c7
Create Date: 2026-03-08 21:39:22.817700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a829c6ec388"
down_revision: Union[str, Sequence[str], None] = "f3d1ff4fb5c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "images", postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "images")
    # ### end Alembic commands ###
