"""create posts table

Revision ID: 53ca878bd911
Revises: 
Create Date: 2026-01-17 19:08:18.457951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53ca878bd911'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('content', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('date_posted', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
                    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')

    # ### end Alembic commands ###
