"""create upvote model

Revision ID: 5b5bc3669197
Revises: 4bcb7810f0e0
Create Date: 2026-02-03 20:59:58.613278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5bc3669197'
down_revision: Union[str, Sequence[str], None] = '4bcb7810f0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upvotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('(post_id IS NOT NULL AND comment_id IS NULL) OR (post_id IS NULL AND comment_id IS NOT NULL)', name='check_only_one_target'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id', name='unique_user_comment_upvote'),
    sa.UniqueConstraint('user_id', 'post_id', name='unique_user_post_upvote')
    )
    op.create_index(op.f('ix_upvotes_comment_id'), 'upvotes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_upvotes_id'), 'upvotes', ['id'], unique=False)
    op.create_index(op.f('ix_upvotes_post_id'), 'upvotes', ['post_id'], unique=False)
    op.create_index(op.f('ix_upvotes_user_id'), 'upvotes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upvotes_user_id'), table_name='upvotes')
    op.drop_index(op.f('ix_upvotes_post_id'), table_name='upvotes')
    op.drop_index(op.f('ix_upvotes_id'), table_name='upvotes')
    op.drop_index(op.f('ix_upvotes_comment_id'), table_name='upvotes')
    op.drop_table('upvotes')
    # ### end Alembic commands ###
