"""add google sub field

Revision ID: af92d955eb78
Revises: 0be6af0e006c
Create Date: 2026-01-24 10:30:23.273876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af92d955eb78'
down_revision: Union[str, Sequence[str], None] = '0be6af0e006c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.add_column('users', sa.Column('google_sub', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_sub')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    # ### end Alembic commands ###
