"""remove upvotes and downvotes table

Revision ID: d386ae97168c
Revises: de09e5b002c9
Create Date: 2026-03-17 07:50:01.517564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd386ae97168c'
down_revision: Union[str, Sequence[str], None] = 'de09e5b002c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downvotes_comment_id'), table_name='downvotes')
    op.drop_index(op.f('ix_downvotes_id'), table_name='downvotes')
    op.drop_index(op.f('ix_downvotes_post_id'), table_name='downvotes')
    op.drop_index(op.f('ix_downvotes_user_id'), table_name='downvotes')
    op.drop_table('downvotes')
    op.drop_index(op.f('ix_upvotes_comment_id'), table_name='upvotes')
    op.drop_index(op.f('ix_upvotes_id'), table_name='upvotes')
    op.drop_index(op.f('ix_upvotes_post_id'), table_name='upvotes')
    op.drop_index(op.f('ix_upvotes_user_id'), table_name='upvotes')
    op.drop_table('upvotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upvotes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint('post_id IS NOT NULL AND comment_id IS NULL OR post_id IS NULL AND comment_id IS NOT NULL', name=op.f('check_only_one_target')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('upvotes_comment_id_fkey')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('upvotes_post_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('upvotes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('upvotes_pkey')),
    sa.UniqueConstraint('user_id', 'comment_id', name=op.f('unique_user_comment_upvote'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', 'post_id', name=op.f('unique_user_post_upvote'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_upvotes_user_id'), 'upvotes', ['user_id'], unique=False)
    op.create_index(op.f('ix_upvotes_post_id'), 'upvotes', ['post_id'], unique=False)
    op.create_index(op.f('ix_upvotes_id'), 'upvotes', ['id'], unique=False)
    op.create_index(op.f('ix_upvotes_comment_id'), 'upvotes', ['comment_id'], unique=False)
    op.create_table('downvotes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint('post_id IS NOT NULL AND comment_id IS NULL OR post_id IS NULL AND comment_id IS NOT NULL', name=op.f('check_only_one_target')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('downvotes_comment_id_fkey')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('downvotes_post_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('downvotes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('downvotes_pkey')),
    sa.UniqueConstraint('user_id', 'comment_id', name=op.f('unique_user_comment_downvote'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', 'post_id', name=op.f('unique_user_post_downvote'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_downvotes_user_id'), 'downvotes', ['user_id'], unique=False)
    op.create_index(op.f('ix_downvotes_post_id'), 'downvotes', ['post_id'], unique=False)
    op.create_index(op.f('ix_downvotes_id'), 'downvotes', ['id'], unique=False)
    op.create_index(op.f('ix_downvotes_comment_id'), 'downvotes', ['comment_id'], unique=False)
    # ### end Alembic commands ###
