"""create downvote model

Revision ID: f3d1ff4fb5c7
Revises: 5b5bc3669197
Create Date: 2026-02-04 21:17:50.423773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d1ff4fb5c7'
down_revision: Union[str, Sequence[str], None] = '5b5bc3669197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('(post_id IS NOT NULL AND comment_id IS NULL) OR (post_id IS NULL AND comment_id IS NOT NULL)', name='check_only_one_target'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id', name='unique_user_comment_downvote'),
    sa.UniqueConstraint('user_id', 'post_id', name='unique_user_post_downvote')
    )
    op.create_index(op.f('ix_downvotes_comment_id'), 'downvotes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_downvotes_id'), 'downvotes', ['id'], unique=False)
    op.create_index(op.f('ix_downvotes_post_id'), 'downvotes', ['post_id'], unique=False)
    op.create_index(op.f('ix_downvotes_user_id'), 'downvotes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downvotes_user_id'), table_name='downvotes')
    op.drop_index(op.f('ix_downvotes_post_id'), table_name='downvotes')
    op.drop_index(op.f('ix_downvotes_id'), table_name='downvotes')
    op.drop_index(op.f('ix_downvotes_comment_id'), table_name='downvotes')
    op.drop_table('downvotes')
    # ### end Alembic commands ###
